before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:1.0 --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:1.0
    - docker push $CI_REGISTRY_IMAGE:latest
